### ISSUE TITLE
Error on data type 109 when running on osu!.db file

### ISSUE THREAD

**Issue by dchurchwell** [pavlukivan/osu-py#1]
Hi there,

I get this error when trying to parse my osu beatmaps file: 

```
>>> import osu
>>> db = osu.OsuDb()
>>> db.load("osu!.db")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Chokfull\.virtualenvs\osudata-aOmEl_9Y\lib\site-packages\osu\osudb.py", line 33, in load
    self.beatmaps.append(BeatmapMetadata.fromOsuDb(self))
  File "C:\Users\Chokfull\.virtualenvs\osudata-aOmEl_9Y\lib\site-packages\osu\beatmapmeta.py", line 62, in fromOsuDb
    self.artistA = osudb.readOsuString()
  File "C:\Users\Chokfull\.virtualenvs\osudata-aOmEl_9Y\lib\site-packages\osu\utility.py", line 162, in readOsuString
    return self.readOsuAny()
  File "C:\Users\Chokfull\.virtualenvs\osudata-aOmEl_9Y\lib\site-packages\osu\utility.py", line 227, in readOsuAny
    raise NotImplementedError(f'Error: attempting to deserialize unknown data type: {t}! Please report this.')
NotImplementedError: Error: attempting to deserialize unknown data type: 109! Please report this.

```

**Comment by chayleaf** [comment]
Interesting, thanks for the report, I'll look into this

**Comment by chayleaf** [comment]
that&s actually super weird, does the file load in osu!? Can you send it to me on discord (pavlukivan#1637, join osu!dev so you can message me) or here? (it pretty much only contains your username and map list)

**Comment by dchurchwell** [comment]
Yeah, not a problem, thanks for taking the time! I'll try running on the other files, too, to see if a similar error comes up.

Do you have a server link for osu!dev?

**Comment by dchurchwell** [comment]
Here's a zip file of the osu!.db
[osu!.zip](https://github.com/pavlukivan/osu-py/files/4006067/osu.zip)

**Comment by chayleaf** [comment]
i can actually reproduce it now, seems like new values were perhaps added, ill check it

**Comment by chayleaf** [comment]
fixed, it was simply copypasted wrong code from another project
